"""Add GST support fields

Revision ID: ed0cc2272b56
Revises: 
Create Date: 2025-11-19 19:06:37.807768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0cc2272b56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('gstin', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('billing_address', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('state_code', sa.String(), nullable=True))
    op.add_column('products', sa.Column('gst_rate', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('hsn_code', sa.String(), nullable=True))
    op.add_column('sale_items', sa.Column('gst_rate', sa.Float(), nullable=True))
    op.add_column('sale_items', sa.Column('hsn_code', sa.String(), nullable=True))
    op.add_column('sale_items', sa.Column('cgst_amount', sa.Float(), nullable=True))
    op.add_column('sale_items', sa.Column('sgst_amount', sa.Float(), nullable=True))
    op.add_column('sale_items', sa.Column('igst_amount', sa.Float(), nullable=True))
    op.add_column('sale_items', sa.Column('line_gst', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('is_gst_inclusive', sa.Boolean(), nullable=True))
    op.add_column('sales', sa.Column('is_interstate', sa.Boolean(), nullable=True))
    op.add_column('sales', sa.Column('cgst_amount', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('sgst_amount', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('igst_amount', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('total_gst', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'total_gst')
    op.drop_column('sales', 'igst_amount')
    op.drop_column('sales', 'sgst_amount')
    op.drop_column('sales', 'cgst_amount')
    op.drop_column('sales', 'is_interstate')
    op.drop_column('sales', 'is_gst_inclusive')
    op.drop_column('sale_items', 'line_gst')
    op.drop_column('sale_items', 'igst_amount')
    op.drop_column('sale_items', 'sgst_amount')
    op.drop_column('sale_items', 'cgst_amount')
    op.drop_column('sale_items', 'hsn_code')
    op.drop_column('sale_items', 'gst_rate')
    op.drop_column('products', 'hsn_code')
    op.drop_column('products', 'gst_rate')
    op.drop_column('customers', 'state_code')
    op.drop_column('customers', 'billing_address')
    op.drop_column('customers', 'gstin')
    # ### end Alembic commands ###

